TLD = cdark
# input files
VERILOG = $(TLD).v
VERILOG += darkriscv.v
VERILOG += darkdemux.v
#VERILOG += config.vh
# frequency
FREQ  = 16

SELFDIR := $(dir $(lastword $(MAKEFILE_LIST)))
include ${SELFDIR}/../Makefile
