FNAME = darksoc
# input files
VERILOG = $(FNAME).v
VERILOG += darkriscv.v
VERILOG += darkdemux.v
#VERILOG += config.vh
# frequency
FREQ  = 8

SELFDIR := $(dir $(lastword $(MAKEFILE_LIST)))
include ${SELFDIR}/../Makefile
