# prolongate the tests as picorv32 is really slow
TMUL = 2

# for VERILOG design files (prepended with ../ and added to IVSIM_VERILOG)
include ../Makefile
# for testbench list and code
include src/Makefile
