TLD = cvex
# input files
VERILOG = $(TLD).v
VERILOG += VexRiscv_smprod_my.v
# VERILOG += VexRiscv_sm_my.v
# VERILOG += VexRiscv_smprod_my_muldiv.v
# frequency
FREQ  = 8


SELFDIR := $(dir $(lastword $(MAKEFILE_LIST)))
include ${SELFDIR}/../Makefile
